name: Lint Commit Messages
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/CHANGELOG.md'
      - '**/package.json'
      - 'lerna.json'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: tradeshift/commitlint-github-action@v3